### PR TITLE
Miscellaneous

### PR DESCRIPTION
**Pull request by itsmebipul00**
In this PR I have added: 
Post Images, Profile(background, dp edit)
Archives(unarchive, reflects in feed)
Drafts(on close icon, delete, post)
Toasts, Loaders
admin@example.com password -> 123456
Or you could make your own profile ;)
All datas persists ;)

### CODE REVIEW

**Review by humzahasan — APPROVED** [review]
- Code changes looks good!
- Really liked the UI, something different. Good work on the loader
- Code structure looks good.

Good to merge!

**Review by tonymike99 — APPROVED** [review]
Hi Bipul,
Nice code. Good to merge

**Review by zoyatanweer — APPROVED** [review]
- code is good and readable

- suggestions on UI :
   1. on signup page, you have button as 'nextxt'. I would suggest you to keep it as 'signup' as on reading 'nextxt' made me think that the spelling of next is wrong.
   2. on the homepage, the floating button is big in size. make it smaller.
   3. in search bar, have some placeholder so as to let the user know what to search.
   4. when signing up from a new account, the HOME page is empty. Have a default text like "follow accounts" etc.
   
  - good to merge with suggested changes.
  - attaching a photo of the floating btn 
  
image

**Comment by itsmebipul00** [comment]
Will make sure to work on suggestion after submission. Thanks for review guys

**Pull request merged**
